# docker file from https://github.com/anibali/docker-pytorch
# installs fastai with all required deps +  opencv + jupyterlab (with git extensions) 
FROM nvidia/cuda:10.0-base-ubuntu18.04

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    sudo \
    git \
    bzip2 \
    libx11-6 \
    build-essential\
 && rm -rf /var/lib/apt/lists/*


# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
#to allow install in /opt
RUN chmod 777 /opt

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user


WORKDIR /home/user

# Install Miniconda
RUN curl -so /opt/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x /opt/miniconda.sh \
 && /opt/miniconda.sh -b -p /opt/miniconda \
 && rm /opt/miniconda.sh
ENV PATH=/opt/miniconda/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

# Create a Python  environment
RUN /opt/miniconda/bin/conda install conda-build \
 && /opt/miniconda/bin/conda create -y --name fastai \
 && /opt/miniconda/bin/conda clean -ya
ENV CONDA_DEFAULT_ENV=fastai
ENV CONDA_PREFIX=/opt/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH

#install pytorch with  CUDA 10.0 and fastai
RUN conda install -y -c  pytorch\
	torchvision cudatoolkit=10.0\
 && conda install -y -c fastai fastai\
 && conda clean -ya

# Install ipykernel
RUN conda install -y ipykernel \
 && conda clean -ya


# Run ipython kernel accessible with ssh after copying kernel info https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh
CMD ipython kernel
